### ISSUE TITLE
TypeError: Cannot read property 'fee' of undefined

### ISSUE THREAD

**Issue by KhmerRun** [Venthos/nodejs-pool#10]
Hello,

I had an issue running this nodejs pool. Blocks found but it doesn't process with payment at all. I installed vi installation script and MyQL. Here are some logs

4|payments | 2018-03-21 12:44 +07:00: Issue checking pool wallet balance before making paymentsundefined
4|payments | 2018-03-21 12:44 +07:00: Will not make more payments until the payment daemon is restarted!
4|payments | 2018-03-21 12:44 +07:00: TypeError: Cannot read property 'fee' of undefined
4|payments |     at /home/lololala/nodejs-pool/lib/payment_systems/itns.js:71:123
4|payments |     at /home/lololala/nodejs-pool/lib/support.js:118:24
4|payments |     at Object.parseBody (/home/lololala/nodejs-pool/node_modules/request-json/main.js:74:12)
4|payments |     at Request._callback (/home/lololala/nodejs-pool/node_modules/request-json/main.js:148:26)
4|payments |     at Request.self.callback (/home/lololala/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
4|payments |     at emitTwo (events.js:126:13)
4|payments |     at Request.emit (events.js:214:7)
4|payments |     at Request.<anonymous> (/home/lololala/nodejs-pool/node_modules/request-json/node_modules/request/request.js:1044:10)
4|payments |     at emitOne (events.js:116:13)
4|payments |     at Request.emit (events.js:211:7)
4|payments |     at IncomingMessage.<anonymous> (/home/lololala/nodejs-pool/node_modules/request-json/node_modules/request/request.js:965:12)
4|payments |     at emitNone (events.js:111:20)
4|payments |     at IncomingMessage.emit (events.js:208:7)
4|payments |     at endReadableNT (_stream_readable.js:1056:12)
4|payments |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
4|payments |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Worker:
/home/lololala/.pm2/logs/worker-error-3.log last 15 lines:
3|worker   | Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:33 +07:00: {}
3|worker   | Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:34 +07:00: {}
3|worker   | Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:35 +07:00: {}
3|worker   | 2018-03-21 13:35 +07:00: Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:36 +07:00: {}
3|worker   | Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:37 +07:00: {}
3|worker   | 2018-03-21 13:37 +07:00: Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:38 +07:00: {}
3|worker   | 2018-03-21 13:38 +07:00: Unable to get wallet stats: Unable to process balance
3|worker   | 2018-03-21 13:39 +07:00: {}
3|worker   | Unable to get wallet stats: Unable to process balance
I could not figure out anything wrong yet.

**Comment by Venthos** [comment]
Looks like you do not have the wallet daemon (intense-wallet-rpc) up and running. Or if you do, you have not set the wallet port in the MySQL "config" table to the correct port.  Check on those two things.  This will help you check what your port is set to for nodejs-pool's config:

`SELECT * from config WHERE module = 'wallet' AND item = 'port';`

**Comment by KhmerRun** [comment]
![image](https://user-images.githubusercontent.com/33341948/37717807-e2396276-2d53-11e8-8b86-67ea43a731e1.png)

My wallet started using:
pm2 start /home/lololala/daemon-itns/bin/intense-wallet-rpc -- --wallet-file XXXXX --password XXXX --daemon-port 48782 --rpc-bind-port 48783 --trusted-daemon

**Comment by KhmerRun** [comment]
<img width="424" alt="untitled" src="https://user-images.githubusercontent.com/33341948/37718423-389c46be-2d55-11e8-8e82-1f5fa7577799.png">

**Comment by Venthos** [comment]
Look at your restart count for intense-wallet-rpc.  Something is wrong and it's endlessly restarting.  Try starting it manually once and seeing what it is upset about.
