### ISSUE TITLE
EADDRNOTAVAIL pool error

### ISSUE THREAD

**Issue by uekdyr** [Venthos/nodejs-pool#12]
Hello, I've got the following error on Pool Daemon "Error: bind EADDRNOTAVAIL myip:3333"

But the selected port "3333" is open and "myip" is my ip.

Also when connecting to the pool with Claymore miner (but on port 7777) it says "Connection failed".

All the daemons says "Online" using the pm2 status command. No errors except the pool error I wrote above.

Reinstalled the package several times, same issue.

Any suggestions?

**Comment by Venthos** [comment]
Either 'myip' is not an IP actually bound to that machine or 3333 is already being utilized by another daemon/service on the server.  If you're using a NAT setup, remember to use the private/internal IP for the 'bind_ip' configuration in config.json and not the public/external IP.  If you're confident that the IP is correct and available, the next step is to run `lsof -iTCP:3333` and see what process may already be listening on that IP/Port, then stop that process.  I am not sure what else could be listening on 3333 unless you have a pool already running on that server, though.

**Comment by bobbieltd** [comment]
In config.json , put bind IP : 0.0.0.0

**Comment by uekdyr** [comment]
> In config.json , put bind IP : 0.0.0.0

@bobbieltd Worked, thank you, cheers!
