### ISSUE TITLE
Karbo Pool Error: Failed to parse block

### ISSUE THREAD

**Issue by CoFix** [Venthos/nodejs-pool#16]
Hi Venthos,

I am using your package.json files and your repo. I am getting this error when any miner connect my pool.
I did try different package json but cant find the problem or cant find true cryptonote-util.

https://images2.imgbox.com/2b/f6/BUw88ZK4_o.png

How can i fix it?

Thank You.

**Comment by Venthos** [comment]
This means that the version of cryptonote-util being used for Karbo is incorrect.  I did not setup a test pool for Karbo so I was relying on Snipa22's original repo working fine.

Try changing `package.json` so that this line:

`"cryptonote-util": "git://github.com/Snipa22/node-cryptonote-util.git#xmr-Nan-2.0",`

looks like this:
`"cryptonote-util": "git://github.com/forknote/node-cryptonote-util.git",`

Then run: `npm install git://github.com/forknote/node-cryptonote-util.git`

Let me know if that works.

**Comment by CoFix** [comment]
Now i am getting this error.

/home/karbo/.pm2/logs/pool-error-7.log last 15 lines:
7|pool     |     at Function.Module._load (module.js:466:25)
7|pool     |     at Module.require (module.js:579:17)
7|pool     |     at require (internal/module.js:11:18)
7|pool     |     at Object.<anonymous> (/home/karbo/nodejs-pool/lib/coins/krb.js:3:16)
7|pool     |     at Module._compile (module.js:635:30)
7|pool     |     at Object.Module._extensions..js (module.js:646:10)
7|pool     |     at Module.load (module.js:554:32)
7|pool     |     at tryModuleLoad (module.js:497:12)
7|pool     |     at Function.Module._load (module.js:489:3)
7|pool     |     at Module.require (module.js:579:17)
7|pool     |     at require (internal/module.js:11:18)
7|pool     |     at /home/karbo/nodejs-pool/init.js:46:15
7|pool     |     at tryCatcher (/home/karbo/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
7|pool     |     at Promise._settlePromiseFromHandler (/home/karbo/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
7|pool     |     at Promise._settlePromise (/home/karbo/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)

**Comment by bobbieltd** [comment]
@CoFix  Venthos is busy with IntenseCoin at the moment. Which repo are you using ? If you are using Venthos’ repo (not Snipa’s), I’ll give you help. Can you post the content of your package.json ?

**Comment by CoFix** [comment]
@bobbieltd I am using Venthos repo and this is my package.json
https://paste.ubuntu.com/p/xwgwq5Y2Kp/

**Comment by bobbieltd** [comment]
Edit nodejs-pool/lib/coin/krb.js
Change const cnUtil = require('cryptonote-util');
to const cnUtil = require('forknote-util');

**Comment by CoFix** [comment]
@bobbieltd nope it doesnt fix it :/ You are online any discord, telegram channel. How can i contact with you?

**Comment by bobbieltd** [comment]
@CoFix Damn ! It didn’t fix it ! Sorry , I can not help you anymore. You need to dig it out by yourself. For hint, you will run into trouble with this coin even when the pool run correctly 😂. Better to choose Monero fork to setup the pool. Avoid forknote coins, you will run into a lot of troubles more than this. I’m on Discord but I’m busy and I can not help you much. I got my own issues to deal with hix.

**Comment by bobbieltd** [comment]
By the way, it should fix issue “failed to parse template” if you change krb.js to “forknote-util”. Package.json should have "forknote-util": "git://github.com/wallet42/node-forknote-util.git"
How many hashrate do you have ? Will you mine with your own pool to test it ? Will you accept to lose money to rent NiceHash ?
What make me laugh that many people asked to setup pools but they never mined on their own pool, they were afraid of losing block reward. They think other miners are stupid and will come to mine on an empty pool. LOL.
For info, I started playing with pool by pointing all my hashing power (small 2-3 kH/s) on other’s pool to test with him. So, I prefer helping serious people not assholes !

**Comment by Venthos** [comment]
Did this get solved/figured out?
