### ISSUE TITLE
systemctl start pm2 failed, cant login /admin.html

### ISSUE THREAD

**Issue by Chinsusu** [Venthos/nodejs-pool#21]
Hi guys, I've tried to setup many times but have the same problem.
systemctl start pm2 failed, at the command 
sudo env PATH=$PATH:`pwd`/.nvm/versions/node/v8.9.3/bin `pwd`/.nvm/versions/node/v8.9.3/lib/node_modules/pm2/bin/pm2 startup systemd -u $CURUSER --hp `pwd`

and I cant login into /admin.html. even I changed the password in db
Pls help me.
thanks

**Comment by Venthos** [comment]
Could you please provide the full error text that happened after the error?

What does `pm2 status` command show when run from the pool user?

**Comment by Chinsusu** [comment]
I fixed it bro @Venthos thanks.

**Comment by Chinsusu** [comment]
![image](https://user-images.githubusercontent.com/29745944/39908804-f921a2e4-5519-11e8-9214-2e6bf5ade67e.png)

this is the issue
