### ISSUE TITLE
"Round Hashes" sometimes does not reset when a block is mined

### ISSUE THREAD

**Issue by Venthos** [Venthos/nodejs-pool#8]
Since "Round Hashes" is only used for a visual indicator of the current round's effort, it has no effect on payouts.  However, it does cause frustration when the current round shows a high percentage even though a block was JUST found.

I do not have a way to reliably reproduce this.  If someone can reliably reproduce this bug, please let me know.  This bug is present in the original nodejs-pool, too.

**Comment by BKdilse** [comment]
I just saw this on my ETN Pool today, and is still an issue.  As you said it's a visual issue, and can worry the miners.  I'm happy to try out non-disruptive checks if you you want?

**Comment by BKdilse** [comment]
Another block has arrived, and effort has still not reset.  I did see a fix on snipa22 repo.  I'll dig it out. 

EDIT:  https://github.com/Snipa22/nodejs-pool/pull/73 is the issue which was fixed... but:
https://github.com/Snipa22/nodejs-pool/commit/be4351401677e25bbcdf7af7e6a25059f202cd13 is the fix, which I can't see in the master: https://github.com/Snipa22/nodejs-pool/blob/master/lib/local_comms.js

You're probably aware, I'm no expert on github, and although kind of understand pulls, merges, etc.  Don't fully.

**Comment by BKdilse** [comment]
To confirm...  I loaded the fix version of local_commn.js, waited for the next block, and boom it resolved the issue.  I have since reverted back to the default local_comms.js.

**Comment by Venthos** [comment]
Thanks.  Pointing to that commit gave me some better insight into how it was originally addressed and where it went wrong.  The fix you pointed to was "lost" when Snipa22 implemented storeBulkShares.  It pretty much confirmed my suspicion that it had to do with a race condition between storeBlock and storeBulkShares.

I have a fix for it, but I am testing it out first to at least make sure the next round resets as normal.
